services:

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 5

  traefik:
    image: traefik:v3.6
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  user-service:
    build:
      context: .
      dockerfile: services/user-service/Dockerfile
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+psycopg://postgres:password@db:5432/user_db
    labels:
      - traefik.enable=true
      - traefik.http.routers.user-service.rule=PathPrefix(`/users`)
      - traefik.http.routers.user-service.entrypoints=web
      - traefik.http.services.user-service.loadbalancer.server.port=8000
  
  order-service:
    build:
      context: .
      dockerfile: services/order-service/Dockerfile
    ports:
      - "8002:8000" # Exposing directly for testing today
    depends_on:
      rabbitmq:
        condition: service_healthy

  db:
    image: postgres:16-alpine

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user_db

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data:
