services:

  user-service:
    build:
      context: .
      dockerfile: services/user-service/DockerFile

    ports:
      - "8001:8000"

    depends_on:
      - db

    environment:
      DATABASE_URL: postgresql+psycopg://postgres:password@db:5432/user_db


  db:
    image: postgres:16-alpine

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user_db

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data: